Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 140
Metrics/ClassLength:
  Max: 120
Metrics/BlockLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Style/Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
